<SettingsSaved>:
    size_hint: 0.75, 0.20
    background: "img/1x1.png"
    title_color: (0,0,0,1)
    title_size: "18sp"
    title: "Settings Saved!"
    SmoothButton:
        border_radius: [10]
        size_hint: 0.6, None
        bg_color: (0.94,0.94,0.94,1)
        color: (0,0,0,1)
        text: "Okay"
        font_size: "20sp"
        height: "40sp"
        halign: "center"
        on_release: root.dismiss()
<SettingsReset>:
    size_hint: 0.75, 0.20
    background: "img/1x1.png"
    title_color: (0,0,0,1)
    title_size: "18sp"
    title: "Settings Reset!"
    SmoothButton:
        border_radius: [10]
        size_hint: 0.6, None
        bg_color: (0.94,0.94,0.94,1)
        color: (0,0,0,1)
        text: "Okay"
        font_size: "20sp"
        height: "40sp"
        halign: "center"
        on_release: root.dismiss()