<SettingsElement@BoxLayout>:
    setting: ""
    description: ""
    value: ""
    padding: "15dp"
    spacing: "10dp"
    size_hint: 1, None
    color: 0,0,0,1
    background_color: (0,0,0,0)
    bg_color: 225/255, 248/255, 1, 1
    background_normal: ''
    back_color:  self.bg_color
    border_radius: [25]
    height: self.minimum_height
    canvas.before:
        Color:
            rgba: self.bg_color
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [(25),(25),(25),(25)]
    BoxLayout:
        orientation: "vertical"
        height: self.minimum_height
        size_hint: 1, None
        pos_hint: {'center_y': 0.5}
        Label:
        Label:
            text_size : self.width, None
            bold: True
            size_hint: 1, None
            height: self.texture_size[1]
            text: root.setting
            color: 0,0,0,1
        Label:
            text_size : self.width, None
            size_hint: 1, None
            height: self.texture_size[1]
            text: root.description
            color: 0,0,0,0.5
        Label:
    TextInput:
        input_filter : 'float'
        height: self.minimum_height
        halign: "center"
        valign: "center"
        id: root.setting
        text: root.value
        on_text: root.value = self.text
        #height: "50sp"
        size_hint_x : 0.2
        size_hint_y: None
        pos_hint: {'center_y': 0.5}
        background_color: 0,0,0,0
        background_normal: "img/1x1.png"
        background_active: "img/1x1.png"
        multiline: False
        cursor_color: 0,0,0,1
        canvas.before:
            Color:
                rgba: (0.5,0.5,0.5,1)
            Line:
                width: 2
                rounded_rectangle: self.x, self.y, self.width, self.height, 25
            Color:
                rgba: 0,0,0,1


<BreakDownLabel>:
    u_type: ""
    u_volume: 0
    orientation: "horizontal"
    padding: "15dp"
    size_hint: 1, None
    color: 0,0,0,1
    background_color: (0,0,0,0)
    bg_color: 225/255, 248/255, 1, 1
    background_normal: ''
    back_color:  self.bg_color
    border_radius: [25]
    height: "70sp"
    canvas.before:
        Color:
            rgba: self.bg_color
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [(25),(25),(25),(25)]
    Label:
        size_hint_y: None
        size_hint_x: 1.76
        text: root.u_type
        font_size: "16dp"
        bold: True
        color: 0,0,0,1
        valign: "center"
        text_size: self.width, None
        height: self.texture_size[1]
        pos_hint: {"center_y":0.5}
    Label:
        text: str(round(root.u_volume, 1)) + " gal"
        text_size: self.size
        halign: "right"
        valign: "center"
        color: 0,0,0,1
    ImageButton:
        height: "30sp"
        size_hint: 1, None
        pos_hint: {"center_y":0.5}
        source: "img/TrashIcon.png"
        on_press: root.delete_water_usage(self.parent.id)
        canvas.before:
            Color:
                rgba: 0, 0, 0, 0.1

<CustomSpinner@Spinner>:
    background_color: (0,0,0,0)
    bg_color : (0.96,0.96,0.96,1)
    color: (0,0,0,1)
    background_normal: ''
    back_color:  self.bg_color if self.state == "normal" else (0.75, 0.75, 0.75, 1)
    border_radius: [25]
    canvas.before:
        Color:
            rgba: self.bg_color if self.state == "normal" else (0.75, 0.75, 0.75, 1)
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [(25),(25),(25),(25)]
        Color:
            rgba: (0.94,0.94,0.94,1)
        Line:
            width: 2
            rounded_rectangle: self.x, self.y, self.width, self.height, 25
<SpinnerOption>:
    background_color: (0,0,0,0)
    bg_color : (0.96,0.96,0.96,1)
    color: (0,0,0,1)
    background_normal: ''
    back_color:  self.bg_color if self.state == "normal" else (0.75, 0.75, 0.75, 1)
    border_radius: [25]
    font_size: "14dp"
    canvas.before:
        Color:
            rgba: self.bg_color if self.state == "normal" else (0.75, 0.75, 0.75, 1)
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [(25),(25),(25),(25)]#[(self.height/2),(self.height/2),(self.height/2),(self.height/2)]
        Color:
            rgba: (0.94,0.94,0.94,1)
        Line:
            width: 2
            rounded_rectangle: self.x, self.y, self.width, self.height, 25
<SmoothButton@Button>:
    background_color: (0,0,0,0)
    bg_color : (0,0,0,1)
    background_normal: ''
    back_color:  self.bg_color if self.state == "normal" else (0, 0, 0, 0.25)
    border_radius: [25]
    canvas.before:
        Color:
            rgba: self.bg_color if self.state == "normal" else (0, 0, 0, 0.25)
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [(25),(25),(25),(25)]

<LabelBorder@Label>:
    canvas.before:
        Color:
            rgba: 0, 0, 0, 1
        Line:
            width: 2
            rectangle: self.x, self.y, self.width, self.height

<BottomBar@Screen>:
    ctrl1:0
    ctrl2:0
    ctrl3:0
    ctrl4:0
    ctrl5:0
    BoxLayout:
        orientation: "horizontal"
        height: "80dp"
        size_hint: 1, None
        padding: dp(5), dp(15), dp(5), dp(20)
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size
        ImageButton:
            size_hint: 1, None
            height: "45dp"
            name: "Info"
            source: "img/PowerOfWaterIcon.png"
            on_release:
                app.close_settings()
                app.root.current = "InfoPage"
                #root.manager.transition.direction = "left"
            canvas.before:
                Color:
                    rgba: 0, 0, 0, 0.1*self.parent.parent.ctrl1
                BoxShadow:
                    pos: self.pos
                    size: self.size
                    spread_radius: 0, 15
                    border_radius: 45, 45, 45, 45

        ImageButton:
            size_hint: 1, None
            height: "45dp"
            name: "Stats"
            source: "img/StatsIcon.png"
            on_release:
                app.close_settings()
                app.root.current = "StatsPage"
                #root.manager.transition.direction = "left"
            canvas.before:
                Color:
                    rgba: 0, 0, 0, 0.1*self.parent.parent.ctrl2
                BoxShadow:
                    pos: self.pos
                    size: self.size
                    spread_radius: 0, 15
                    border_radius: 45, 45, 45, 45

        ImageButton:
            size_hint: 1, None
            height: "45dp"
            name: "Home"
            source: "img/HomeIcon.png"
            on_release:
                app.close_settings()
                app.root.current = "HomePage"
                #root.manager.transition.direction = "left"
            canvas.before:
                Color:
                    rgba: 0, 0, 0, 0.1*self.parent.parent.ctrl3
                BoxShadow:
                    pos: self.pos
                    size: self.size
                    spread_radius: 0, 15
                    border_radius: 45, 45, 45, 45
        ImageButton:
            size_hint: 1, None
            height: "45dp"
            name: "Timer"
            source: "img/TimerIcon.png"
            on_release:
                app.close_settings()
                app.root.current = "TimerPage"
                #root.manager.transition.direction = "left"
            canvas.before:
                Color:
                    rgba: 0, 0, 0, 0.1*self.parent.parent.ctrl4
                BoxShadow:
                    pos: self.pos
                    size: self.size
                    spread_radius: 0, 15
                    border_radius: 45, 45, 45, 45
        ImageButton:
            size_hint: 1, None
            height: "45dp"
            name: "Settings"
            source: "img/SettingsIcon.png"
            on_release:
                #app.open_settings()
                app.root.current = "SettingsPage"
                #root.manager.transition.direction = "left"
            canvas.before:
                Color:
                    rgba: 0, 0, 0, 0.1*self.parent.parent.ctrl5
                BoxShadow:
                    pos: self.pos
                    size: self.size
                    spread_radius: 0, 15
                    border_radius: 45, 45, 45, 45
<WhiteBoxLayout@BoxLayout>:
    padding: dp(25),dp(60),dp(25),dp(10)
    orientation: "vertical"
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size