<InfoPage>:
    name : "InfoPage"
    BoxLayout:
        orientation: "vertical"
        padding: sp(0),sp(0),sp(0),sp(10)
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size
        ScrollView:
            size_hint_y: 100
            WhiteBoxLayout:
                height: self.minimum_height
                size_hint_y: None
                spacing: "15dp"
                orientation: "vertical"
                Label:
                    text: "Info"
                    text_size : self.width, None
                    size_hint: 1, None
                    height: self.texture_size[1]
                    halign: "left"
                    valign: "top"
                    font_size: "30sp"
                    bold: True
                    color: 0,0,0,1
                SmoothButton:
                    bg_color: 225/255, 248/255, 1, 1
                    size_hint: 1, None
                    height: "70sp"
                    text: "Donate Now!"
                    font_size: "20sp"
                    color: 0,0,0,1
                    bold: True
                    on_release: root.donate()
                BoxLayout:
                    height: self.minimum_height
                    size_hint_y: None
                    padding: "15dp"
                    spacing: "10dp"
                    size_hint: 1, None
                    orientation: "vertical"
                    canvas.before:
                        Color:
                            rgba: 244/255, 251/255, 1, 1
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [(25,25),(25,25),(25,25),(25,25)]
                    Label:
                        text: "About The Power of Clean Water"
                        bold: True
                        font_size: "20sp"
                        color: 0,0,0,1
                        size_hint: 1, None
                        height: self.texture_size[1]
                        text_size: self.size
                    Label:
                        text: "The Power of Clean Water connects young people to the global water crisis and empowers them to help. By providing the tools and the water projects in need of funding, we provide a clear path to making a difference in the world."
                        size_hint_y: None
                        font_size: "12dp"
                        color: 0,0,0,1
                        text_size: self.width, None
                        height: self.texture_size[1]

                BoxLayout:
                    height: self.minimum_height
                    size_hint_y: None
                    padding: "15dp"
                    spacing: "10dp"
                    size_hint: 1, None
                    orientation: "vertical"
                    canvas.before:
                        Color:
                            rgba: 244/255, 251/255, 1, 1
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [(25,25),(25,25),(25,25),(25,25)]
                    Label:
                        text: "About The WaterTrack App"
                        bold: True
                        font_size: "20sp"
                        color: 0,0,0,1
                        size_hint: 1, None
                        height: self.texture_size[1]
                        text_size: self.size
                    Label:
                        text: "The WaterTrack App aims to assist users in realizing the amount of water they are using. This is done by making it easy to enter daily usage and track water usage while doing day to day activities"
                        size_hint_y: None
                        font_size: "12dp"
                        color: 0,0,0,1
                        text_size: self.width, None
                        height: self.texture_size[1]
                BoxLayout:
                    height: self.minimum_height
                    size_hint_y: None
                    padding: "15dp"
                    spacing: "10dp"
                    size_hint: 1, None
                    orientation: "vertical"
                    canvas.before:
                        Color:
                            rgba: 244/255, 251/255, 1, 1
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [(25,25),(25,25),(25,25),(25,25)]
                    Label:
                        text: "Credits"
                        bold: True
                        font_size: "20sp"
                        color: 0,0,0,1
                        size_hint: 1, None
                        height: self.texture_size[1]
                        text_size: self.size
                    Label:
                        #multiline:True
                        size_hint_y: None
                        text: "Info Icon: https://www.flaticon.com/free-icons/info\nBar Graph/Statistics icon: https://www.flaticon.com/free-icons/increase\nHome Icon: https://www.flaticon.com/free-icons/home\nTimer Icon: https://www.flaticon.com/free-icons/timer\nSettings Icon:https://www.flaticon.com/free-icons/settings\nPause Icon: https://www.flaticon.com/free-icons/pause\nRestart Icon: https://www.flaticon.com/free-icons/reset\nTrash Icon: https://www.flaticon.com/free-icons/trash\n"
                        font_size: "10dp"
                        color: 0,0,0,1
                        text_size: self.width, None
                        height: self.texture_size[1]
                Label:
                    font_size: "18sp"
                    text: "Created by Aum Shah\n\n"
                    bold: True
                    size_hint_y: None
                    height: self.texture_size[1]
                    color: 0,0,0,1
        BottomBar:
            ctrl1:1
