<StatsPage>:
    name : "StatsPage"
    BoxLayout:
        orientation: "vertical"
        padding: sp(0),sp(0),sp(0),sp(10)
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size
        ScrollView:
            size_hint_y: 100
            WhiteBoxLayout:
                id: layout
                height: self.minimum_height
                size_hint_y: None
                spacing: "12.5dp"
                orientation: "vertical"
                #pos_hint: {"top":0}
                #canvas.before:
                #    Color:
                #        rgba: 0, 0, 0, 1
                #    Line:
                #        width: 2
                #        rectangle: self.x, self.y, self.width, self.height
                Label:
                    text: "Stats"
                    text_size : self.width, None
                    size_hint: 1, None
                    height: self.texture_size[1]
                    halign: "left"
                    valign: "top"
                    font_size: "30sp"
                    bold: True
                    color: 0,0,0,1
                BoxLayout:
                    height: self.minimum_height
                    size_hint: 1, None
                    padding: sp(5),sp(10),sp(5),sp(10)
                    spacing: "10dp"
                    orientation: "vertical"
                    canvas.before:
                    #    Color:
                    #        rgba: 0, 0, 0, 1
                    #    Line:
                    #        width: 2
                    #        rectangle: self.x, self.y, self.width, self.height
                        Color:
                            rgba: 244/255, 251/255, 1, 1
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [(25,25),(25,25),(25,25),(25,25)]
                    Label:
                        text: "This Week's Water Usage"
                        halign: "center"
                        bold: True
                        font_size: "18dp"
                        color: 0,0,0,1
                        size_hint: 1, None
                        height: self.texture_size[1]
                        text_size: self.size
                    Image:
                        id: StatsImage
                        pos_hint : {"center_x": 0.5}
                        size_hint: 1, None
                        allow_stretch: True
                    Image:
                        id: Key
                        source: "img/StatsLegend.png"
                        pos_hint : {"center_x": 0.5}
                        size_hint: 1, None
                        allow_stretch: True

                BoxLayout:
                    height: self.minimum_height
                    padding: sp(15),sp(10),sp(15),sp(10)
                    spacing: "10dp"
                    size_hint: 1, None
                    orientation: "vertical"
                    canvas.before:
                        Color:
                            rgba: 244/255, 251/255, 1, 1
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [(25,25),(25,25),(25,25),(25,25)]
                    Label:
                        text: "Summary"
                        bold: True
                        font_size: "18dp"
                        color: 0,0,0,1
                        size_hint: 1, None
                        height: self.texture_size[1]
                        text_size: self.size
                    Label:
                        id: avg
                        text: "Average water usage"
                        text_size : self.width, None
                        size_hint: 1, None
                        height: self.texture_size[1]
                        halign: "left"
                        valign: "top"
                        font_size: "14dp"
                        bold: True
                        color: 0,0,0,1
                    Label:
                        id: max
                        text: "Max water usage"
                        text_size : self.width, None
                        size_hint: 1, None
                        height: self.texture_size[1]
                        halign: "left"
                        valign: "top"
                        font_size: "14dp"
                        bold: True
                        color: 0,0,0,1
                    Label:
                        id: min
                        text: "Min water usage"
                        text_size : self.width, None
                        size_hint: 1, None
                        height: self.texture_size[1]
                        halign: "left"
                        valign: "top"
                        font_size: "14dp"
                        bold: True
                        color: 0,0,0,1
        BottomBar:
            ctrl2:1